apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template: 
    metadata: # Dictionary
      name: myapp1-pod
      labels: # Dictionary 
        app: myapp1        
    spec:
      containers: # List
        - name: myapp1-container
          image: lwplapbs/myapp1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: myapp1-service
spec:
  type: LoadBalancer
  selector: 
    app: myapp1
  ports: 
    - name: http
      port: 80
      targetPort: 80
