apiVersion: v1
kind: Service
metadata:
  name: dev-wordpress
  namespace: "hr"
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: dev-wordpress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: dev-wordpress
