apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::113768732838:role/eksctl-eks-cluster-nodegroup-eks-NodeInstanceRole-186GWKPW93OVH
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::113768732838:user/ashok
      username: ashok
