apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources: 
    requests:
      storage: 4Gi
