---
# Source: drupal/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-drupal
  labels:
    app.kubernetes.io/name: drupal
    helm.sh/chart: drupal-11.0.21
    app.kubernetes.io/instance: dev-drupal
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: drupal
      app.kubernetes.io/instance: dev-drupal
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drupal
        helm.sh/chart: drupal-11.0.21
        app.kubernetes.io/instance: dev-drupal
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/port: "9117"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: dev-drupal
          image: docker.io/bitnami/drupal:9.3.9-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
            - name: DRUPAL_DATABASE_HOST
              value: "dev-drupal-mariadb"
            - name: DRUPAL_DATABASE_PORT_NUMBER
              value: "3306"
            - name: DRUPAL_DATABASE_NAME
              value: "bitnami_drupal"
            - name: DRUPAL_DATABASE_USER
              value: "bn_drupal"
            - name: DRUPAL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-drupal-mariadb
                  key: "mariadb-password"
            - name: DRUPAL_SKIP_BOOTSTRAP
              value: "no"
            - name: DRUPAL_PROFILE
              value: "standard"
            - name: DRUPAL_USERNAME
              value: "user"
            - name: DRUPAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-drupal
                  key: drupal-password
            - name: DRUPAL_EMAIL
              value: "user@example.com"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /user/login
              port: http
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /user/login
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits: {}
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: drupal-data
              mountPath: /bitnami/drupal
      volumes:
        - name: drupal-data
          persistentVolumeClaim:
            claimName: dev-drupal-drupal