apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.21"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group-v2
    instanceType: t2.medium
    desiredCapacity: 3
    privateNetworking: true
