apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp2
  template: 
    metadata: # Dictionary
      name: myapp2-pod
      labels: # Dictionary 
        app: myapp2        
    spec:
      containers: # List
        - name: myapp2-container
          image: lwplapbs/myapp2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: myapp2-service
spec:
  type: ClusterIP 
  selector: 
    app: myapp2
  ports: 
    - name: http
      port: 80
      targetPort: 80
---      
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp2
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "lwplabs.sites.team"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: myapp2-service
            port:
              number: 80
