apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.21"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group-spot-instances
    desiredCapacity: 2
    privateNetworking: true
    instancesDistribution:
      instanceTypes: ["t3.medium", "t3a.medium"]
      onDemandPercentageAboveBaseCapacity: 0
    labels: { lifecycle: Ec2Spot }
